/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

/**
 *
 * @author ASUS TUF
 */
 import javax.swing.JFrame;
import javax.swing.ImageIcon;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;



public class calculator extends JFrame {
    


    /**
     * Creates new form calculator
     */
    
    double NumEnter1;
    double NumEnter2;
    double Result;
    String op;
    
    public calculator() {
        initComponents();
     ImageIcon icon = new ImageIcon(getClass().getResource("/kgp.png"));
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        ardigit7 = new javax.swing.JButton();
        ardigit3 = new javax.swing.JButton();
        ardigit2 = new javax.swing.JButton();
        ardigit5 = new javax.swing.JButton();
        ardigit0 = new javax.swing.JButton();
        ardigit4 = new javax.swing.JButton();
        ardigit6 = new javax.swing.JButton();
        ardigit9 = new javax.swing.JButton();
        ardigit1 = new javax.swing.JButton();
        arCE = new javax.swing.JButton();
        arM = new javax.swing.JButton();
        arD = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        arP = new javax.swing.JButton();
        arC = new javax.swing.JButton();
        ardigit8 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        arT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("arif reze");
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 290, 90));

        ardigit7.setBackground(new java.awt.Color(0, 255, 255));
        ardigit7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ardigit7.setText("7");
        ardigit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ardigit7ActionPerformed(evt);
            }
        });
        getContentPane().add(ardigit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 40, 40));

        ardigit3.setBackground(new java.awt.Color(128, 128, 128));
        ardigit3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ardigit3.setText("3");
        ardigit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ardigit3ActionPerformed(evt);
            }
        });
        getContentPane().add(ardigit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 40, 40));

        ardigit2.setBackground(new java.awt.Color(255, 0, 255));
        ardigit2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ardigit2.setText("2");
        ardigit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ardigit2ActionPerformed(evt);
            }
        });
        getContentPane().add(ardigit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 40, 40));

        ardigit5.setBackground(new java.awt.Color(255, 0, 255));
        ardigit5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ardigit5.setText("5");
        ardigit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ardigit5ActionPerformed(evt);
            }
        });
        getContentPane().add(ardigit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 40, 40));

        ardigit0.setBackground(new java.awt.Color(255, 255, 0));
        ardigit0.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ardigit0.setText("0");
        ardigit0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ardigit0ActionPerformed(evt);
            }
        });
        getContentPane().add(ardigit0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 40, 40));

        ardigit4.setBackground(new java.awt.Color(0, 255, 255));
        ardigit4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ardigit4.setText("4");
        ardigit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ardigit4ActionPerformed(evt);
            }
        });
        getContentPane().add(ardigit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 40, 40));

        ardigit6.setBackground(new java.awt.Color(128, 128, 128));
        ardigit6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ardigit6.setText("6");
        ardigit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ardigit6ActionPerformed(evt);
            }
        });
        getContentPane().add(ardigit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 40, 40));

        ardigit9.setBackground(new java.awt.Color(128, 128, 128));
        ardigit9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ardigit9.setText("9");
        ardigit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ardigit9ActionPerformed(evt);
            }
        });
        getContentPane().add(ardigit9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 40, 40));

        ardigit1.setBackground(new java.awt.Color(0, 255, 255));
        ardigit1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ardigit1.setText("1");
        ardigit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ardigit1ActionPerformed(evt);
            }
        });
        getContentPane().add(ardigit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 40, 40));

        arCE.setBackground(new java.awt.Color(165, 42, 42));
        arCE.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        arCE.setForeground(new java.awt.Color(255, 192, 203));
        arCE.setText("BS");
        arCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arCEActionPerformed(evt);
            }
        });
        getContentPane().add(arCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 60, 40));

        arM.setBackground(new java.awt.Color(0, 255, 0));
        arM.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        arM.setText("-");
        arM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arMActionPerformed(evt);
            }
        });
        getContentPane().add(arM, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 60, 40));

        arD.setBackground(new java.awt.Color(0, 255, 0));
        arD.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        arD.setText("÷");
        arD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arDActionPerformed(evt);
            }
        });
        getContentPane().add(arD, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 60, 40));

        jButton13.setBackground(new java.awt.Color(0, 255, 0));
        jButton13.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButton13.setText("=");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 90, 40));

        arP.setBackground(new java.awt.Color(0, 255, 0));
        arP.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        arP.setText("+");
        arP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arPActionPerformed(evt);
            }
        });
        getContentPane().add(arP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 60, 40));

        arC.setBackground(new java.awt.Color(255, 0, 0));
        arC.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        arC.setForeground(new java.awt.Color(0, 0, 255));
        arC.setText("C");
        arC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arCActionPerformed(evt);
            }
        });
        getContentPane().add(arC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 60, 40));

        ardigit8.setBackground(new java.awt.Color(255, 0, 255));
        ardigit8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ardigit8.setText("8");
        ardigit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ardigit8ActionPerformed(evt);
            }
        });
        getContentPane().add(ardigit8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 40, 40));

        jButton17.setBackground(new java.awt.Color(0, 0, 128));
        jButton17.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButton17.setForeground(new java.awt.Color(0, 255, 255));
        jButton17.setText(".");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 80, 40));

        arT.setBackground(new java.awt.Color(128, 128, 0));
        arT.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        arT.setText("x");
        arT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arTActionPerformed(evt);
            }
        });
        getContentPane().add(arT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 60, 40));

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("ARIFREZE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  private void EnterNumbers(String q)
    {
        String Nums = jTextField1.getText() + q;
        jTextField1.setText(Nums);
    }
    private void ardigit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ardigit7ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("7");
    }//GEN-LAST:event_ardigit7ActionPerformed

    private void ardigit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ardigit0ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("0");
    }//GEN-LAST:event_ardigit0ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ardigit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ardigit3ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("3");
    }//GEN-LAST:event_ardigit3ActionPerformed

    private void ardigit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ardigit2ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("2");
    }//GEN-LAST:event_ardigit2ActionPerformed
   
    private void arCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arCEActionPerformed
        // TODO add your handling code here:
        
        String bs = null;
        
        if (jTextField1.getText().length() > 0)
        {
            StringBuilder sb = new StringBuilder(jTextField1.getText());
            sb.deleteCharAt(jTextField1.getText().length() - 1);
            bs = sb.toString();
            jTextField1.setText(bs);
        }
    }//GEN-LAST:event_arCEActionPerformed

    private void arPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arPActionPerformed
        // TODO add your handling code here:
        NumEnter1 = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        op = "+";
    }//GEN-LAST:event_arPActionPerformed

    private void arCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arCActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        
        String Fn, Sn;
        
        Fn = String.valueOf(NumEnter1);
        Sn = String.valueOf(NumEnter2);
        
        Fn ="";
        Sn ="";
    }//GEN-LAST:event_arCActionPerformed

    private void ardigit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ardigit8ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("8");
    }//GEN-LAST:event_ardigit8ActionPerformed

    private void ardigit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ardigit1ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("1");
    }//GEN-LAST:event_ardigit1ActionPerformed

    private void ardigit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ardigit4ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("4");
    }//GEN-LAST:event_ardigit4ActionPerformed

    private void ardigit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ardigit5ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("5");
    }//GEN-LAST:event_ardigit5ActionPerformed

    private void ardigit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ardigit6ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("6");
    }//GEN-LAST:event_ardigit6ActionPerformed

    private void ardigit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ardigit9ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("9");
    }//GEN-LAST:event_ardigit9ActionPerformed

    private void arDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arDActionPerformed
        // TODO add your handling code here:
       NumEnter1 = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        op = "÷";
    }//GEN-LAST:event_arDActionPerformed

    private void arTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arTActionPerformed
        // TODO add your handling code here:
        NumEnter1 = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        op = "x";
    }//GEN-LAST:event_arTActionPerformed

    private void arMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arMActionPerformed
        // TODO add your handling code here:
        NumEnter1 = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        op = "-";
    }//GEN-LAST:event_arMActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        
        if(! jTextField1.getText().contains("."))
        {
            jTextField1.setText(jTextField1.getText() + jButton17.getText());
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
     NumEnter2 = Double.parseDouble(jTextField1.getText()); 

    // Format NumEnter1 and NumEnter2 based on whether they are whole numbers or not
    String formattedNumEnter1 = (NumEnter1 % 1 == 0) ? String.format("%.0f", NumEnter1) : String.format("%.2f", NumEnter1);
    String formattedNumEnter2 = (NumEnter2 % 1 == 0) ? String.format("%.0f", NumEnter2) : String.format("%.2f", NumEnter2);

    // Prepare the expression string with the formatted numbers
    String expression = formattedNumEnter1 + " " + op + " " + formattedNumEnter2;

    // Perform the operation based on the current operator
    switch (op) {
        case "+":
            Result = NumEnter1 + NumEnter2;
            break;
        case "-":
            Result = NumEnter1 - NumEnter2;
            break;
        case "x":
            Result = NumEnter1 * NumEnter2;
            break;
        case "÷":
            // Handle division by zero
            if (NumEnter2 == 0) {
                jTextField1.setText("Cannot divide by zero");
                return;
            }
            Result = NumEnter1 / NumEnter2;
            break;
        default:
            // Invalid operator case
            jTextField1.setText("Error: Invalid operation");
            return;
    }

    // Prepare the final output string for Result
    String formattedResult = (Result % 1 == 0) ? String.format("%.0f", Result) : String.format("%.2f", Result);
    
    // Output: expression with result
    String output = expression + " = " + formattedResult;

    // Update text field with the complete expression and result
    jTextField1.setText(output);
    
    // Reset NumEnter1 to Result for further calculations
    NumEnter1 = Result;

    // Clear op for next operation (if needed)
    op = "";
    
    
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arC;
    private javax.swing.JButton arCE;
    private javax.swing.JButton arD;
    private javax.swing.JButton arM;
    private javax.swing.JButton arP;
    private javax.swing.JButton arT;
    private javax.swing.JButton ardigit0;
    private javax.swing.JButton ardigit1;
    private javax.swing.JButton ardigit2;
    private javax.swing.JButton ardigit3;
    private javax.swing.JButton ardigit4;
    private javax.swing.JButton ardigit5;
    private javax.swing.JButton ardigit6;
    private javax.swing.JButton ardigit7;
    private javax.swing.JButton ardigit8;
    private javax.swing.JButton ardigit9;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
